ALTER TABLE physical_face_project_account
    ALTER COLUMN BIC TYPE BIGINT USING BIC::BIGINT,
    ALTER COLUMN checking_account TYPE BIGINT USING checking_account::BIGINT,
    ALTER COLUMN correspondent_account TYPE BIGINT USING correspondent_account::BIGINT,
    ALTER COLUMN INN TYPE BIGINT USING INN::BIGINT;

ALTER TABLE juridical_face_project_accout
    ALTER COLUMN BIC TYPE BIGINT USING BIC::BIGINT,
    ALTER COLUMN checking_account TYPE BIGINT USING checking_account::BIGINT,
    ALTER COLUMN correspondent_account TYPE BIGINT USING correspondent_account::BIGINT,
    ALTER COLUMN INN TYPE BIGINT USING INN::BIGINT,
    ALTER COLUMN OGRN TYPE BIGINT USING OGRN::BIGINT;

ALTER TABLE ip_project_account
    ALTER COLUMN BIC TYPE BIGINT USING BIC::BIGINT,
    ALTER COLUMN ras_schot TYPE BIGINT USING ras_schot::BIGINT,
    ALTER COLUMN kor_schot TYPE BIGINT USING kor_schot::BIGINT,
    ALTER COLUMN INN TYPE BIGINT USING INN::BIGINT,
    ALTER COLUMN OGRN TYPE BIGINT USING OGRN::BIGINT;
