ALTER TABLE physical_face_project_account
    ALTER COLUMN BIC TYPE VARCHAR(50),
    ALTER COLUMN checking_account TYPE VARCHAR(50),
    ALTER COLUMN correspondent_account TYPE VARCHAR(50),
    ALTER COLUMN INN TYPE VARCHAR(50);

ALTER TABLE juridical_face_project_accout
    ALTER COLUMN BIC TYPE VARCHAR(50),
    ALTER COLUMN checking_account TYPE VARCHAR(50),
    ALTER COLUMN correspondent_account TYPE VARCHAR(50),
    ALTER COLUMN INN TYPE VARCHAR(50),
    ALTER COLUMN OGRN TYPE VARCHAR(50);

ALTER TABLE ip_project_account
    ALTER COLUMN BIC TYPE VARCHAR(50),
    ALTER COLUMN ras_schot TYPE VARCHAR(50),
    ALTER COLUMN kor_schot TYPE VARCHAR(50),
    ALTER COLUMN INN TYPE VARCHAR(50),
    ALTER COLUMN OGRN TYPE VARCHAR(50);
